### ISSUE TITLE
External player: watched status cannot be synched

### ISSUE THREAD

**Issue by JCalvi** [croneter/PlexKodiConnect#1023]
Hi again Croneter,

I have a strange issue with watched status not syncing correctly.
After a fair bit of troubleshooting here is what happens.
1. I launch Kodi
2. I watch a file that is linked via PKC via an external player (I use Zoomplayer).
3. The video file may be over an hour so PKC waits to run a scheduled sync.
3. I finish watching the video and close the external player and the item is marked as watched for a second or so.
4. PKC runs its scheduled sync and changes the watched back to unwatched.

I can repeat this behaviour quickly by...
1. Watch a file by skipping forward near end.
2. Close player
3. Run a Manual PKC sync.

Notes of interest.
1. I have tried various levels of DB cleaning and resetting - no difference.
2. If I mark the file watched manually using Kodi (W) then it syncs correctly even though the watched tick is the same in both instances
3. There appears to be a thread about a similar issue in emby?
https://emby.media/community/index.php?/topic/52761-watched-status-not-set-using-external-player-androidtvupnp-stream/page-4
4. I couldn't see anything of value in the logs but will endeavour to set to debug and see if I can find something helpful there.

**Comment by JCalvi** [comment]
Here is a debug log.
I played 2 files, S03E01 & S03E02.
The first one marked as watched and stayed watched after a manual sync.
The second one marked as watched and reset to un-watched after a manual sync.
  
[kodi-debug.zip](https://github.com/croneter/PlexKodiConnect/files/3783483/kodi-debug.zip)

**Comment by croneter** [comment]
Does the video stay correctly watched on the Plex Media Server side?

**Comment by croneter** [comment]
I guess PKC is simply not able to tell what the external player is doing, thus not telling the PMS about the watch progress...

**Comment by croneter** [comment]
Does not look good:
> There's no solution to this. Kodi simply doesn't trigger any events the add-on can hook onto to detect playback status of any kind.

**Comment by JCalvi** [comment]
Later in this thread they seem to find a resolution though. 

It must be doable as Kodi marks the item as watched fine, I have not checked yet directly but assume this is written into Kodi’s sql database. 

PKC then overwrites it when it syncs to PMS as it seems to see this watched status differently to others. I’ll check the Kodi dB when I get a minute to see what the difference is.

**Comment by JCalvi** [comment]
Ok, I have done some troubleshooting

1. The external player marks the item correctly as watched.

2. The Kodi Database get set as follows
idFile	idPath	strFilename	playCount	lastPlayed	                dateAdded
1997	786	Veep S03E01.mkv	1	               2019-11-02 17:48:29	2019-02-12 21:04:30

3. After a PKC Sync the item is returned to not watched and the Kodi Database contains
idFile	idPath	strFilename	playCount	lastPlayed	                dateAdded
1997	786	Veep S03E01.mkv			                                                2019-02-12 21:04:30

4. If I set the item to Watched through the Kodi Menu the database is again set as
idFile	idPath	strFilename	playCount	lastPlayed	                dateAdded
1997	786	Veep S03E01.mkv	1	                2019-11-02 17:55:33	2019-02-12 21:04:30

So no real difference here, except PKC correctly handles the menu driven sync and not the exteranl player derived one. 

Note: the main database file MyVideos116.db does not get updated as changes are being tracked in MyVideos116.db-wal combined with the base database.

My question then is PKC looking for events to sync watched status rather than looking directly at the Kodi database and checking playCount? If it was getting the play status from the Kodi database then there would not be any issues. It would need to track changes in both directions though which I understand can be tricky. 

If you are using an event driven model then perhaps after play has stopped which is a Kodi event perhaps check the database for playCount for the just stopped item and then and if greater than zero trigger a watched sync to PMS.

JC.

**Comment by JCalvi** [comment]
I have tried the latest 2.10.0 and this version with the fix resume has not fixed this issue. 

I updated to 2.10.0, played a file, this marked it as watched, then I ran a manual sync and the item reset to unwatched.

**Comment by croneter** [comment]
That is because the pull request has not yet been merged. You'll need to wait for 2.10.1

**Comment by JCalvi** [comment]
Ok, no worries. 

Thanks again.

**Comment by croneter** [comment]
Should be solved with PKC version 2.10.1

**Comment by JCalvi** [comment]
Thx Croneter,

Works like a charm.

Cheers!

**Comment by croneter** [comment]
Thanks for the feedback. And for the beer! :wink:

**Comment by JCalvi** [comment]
Hi croneter,
Unfortunately I am still seeing the same issue.
I can recreate it.
1 Play a file with external player for about 20 mins or more.
2. Stop the file when > 90%
3. The file is marked as played in Kodi
4. Leave the page in Kodi and come back to it.
5. The file shows as unwatched again.
6. Manually toggle the file as watched.
7. The file stays watched from then on.

I captured a log but cannot see any reason why this happens.
2020-04-12 12:47:22.917 T:13640  NOTICE: PLEX.plex_functions: Toggled watched state for Plex item 30851
This happens when the player is stopped and there is no other log as to why it gets changed afterwards. It is fairly annoying as everything looks ok, and only when you leave the page and come back do you see it was not marked as watched correctly.

JC.

**Comment by JCalvi** [comment]
croneter,

I took a look today and it looks like its in kodimonitor.py
Line 411
```
    if status['external_player']:
        _external_player_correct_plex_watch_count(db_item)
        progress = 0.0
        time = 0.0
```


You call  _external_player_correct_plex_watch_count(db_item)
but then set progress and time to 0 on the next 2 lines.

Then at line 434

```
    if time < v.IGNORE_SECONDS_AT_START:
        LOG.debug('Ignoring playback less than %s seconds',
                  v.IGNORE_SECONDS_AT_START)
        # Annoying Plex bug - it'll reset an already watched video to unwatched
        playcount = None
        last_played = None
        time = 0
```

You reset playcount if time < v.IGNORE_SECONDS_AT_START which it will be as it has been set to zero.

If I comment the progress and time = 0 out it works for me again.

This could probably be better but I have done this for now and it seems to generally work ok...
From Line 411

```
    if not status['external_player']:
        if ended:
            progress = 0.99
            time = v.IGNORE_SECONDS_AT_START + 1
        else:
            time = float(timing.kodi_time_to_millis(status['time'])) / 1000
            try:
                progress = time / totaltime
            except ZeroDivisionError:
                progress = 0.0
            LOG.debug('Playback progress %s (%s of %s seconds)',
                      progress, time, totaltime)
    playcount = status['playcount']
    last_played = timing.kodi_now()
    if playcount is None:
        LOG.debug('playcount not found, looking it up in the Kodi DB')
        with kodi_db.KodiVideoDB() as kodidb:
            playcount = kodidb.get_playcount(db_item['kodi_fileid'])
        playcount = 0 if playcount is None else playcount 
    if not status['external_player']:
        if time < v.IGNORE_SECONDS_AT_START:
            LOG.debug('Ignoring playback less than %s seconds',
                      v.IGNORE_SECONDS_AT_START)
            # Annoying Plex bug - it'll reset an already watched video to unwatched
            playcount = None
            last_played = None
            time = 0
        elif progress >= v.MARK_PLAYED_AT:
            LOG.debug('Recording entirely played video since progress > %s',
                      v.MARK_PLAYED_AT)
            playcount += 1
            time = 0
```

And also deleted...
```
def _external_player_correct_plex_watch_count(db_item):
    """
    Kodi won't safe playstate at all for external players

    There's currently no way to get a resumpoint if an external player is
    in use  We are just checking whether we should mark video as
    completely watched or completely unwatched (according to
    playcountminimumtime set in playercorefactory.xml)
    See https://kodi.wiki/view/External_players
    """
    with kodi_db.KodiVideoDB() as kodidb:
        playcount = kodidb.get_playcount(db_item['kodi_fileid'])
    LOG.debug('External player detected. Playcount: %s', playcount)
    PF.scrobble(db_item['plex_id'], 'watched' if playcount else 'unwatched')
```

As I don't think its required as your other code does the same thing anyway.



JC.

**Comment by JCalvi** [comment]
croneter,

I took a look today and it looks like its in kodimonitor.py
Line 411
```
    if status['external_player']:
        _external_player_correct_plex_watch_count(db_item)
        progress = 0.0
        time = 0.0
```


You call  _external_player_correct_plex_watch_count(db_item)
but then set progress and time to 0 on the next 2 lines.

Then at line 434

```
    if time < v.IGNORE_SECONDS_AT_START:
        LOG.debug('Ignoring playback less than %s seconds',
                  v.IGNORE_SECONDS_AT_START)
        # Annoying Plex bug - it'll reset an already watched video to unwatched
        playcount = None
        last_played = None
        time = 0
```

You reset playcount if time < v.IGNORE_SECONDS_AT_START which it will be as it has been set to zero.

If I comment the progress and time = 0 out it works for me again.

This could probably be better but I have done this for now and it seems to generally work ok...
From Line 411

```
    if status['external_player']:
        _external_player_correct_plex_watch_count(db_item)
        progress = 0.99
        time = v.IGNORE_SECONDS_AT_START + 1
    else:
```




JC.

**Comment by JCalvi** [comment]
Sorry, did not mean to close issue.

Also updated above as previous comment was incorrect (playstate reset on library update with that one).

JC

**Comment by croneter** [comment]
Can you please share your entire code?

**Comment by JCalvi** [comment]
I only changed line 413 and 414

From:

```
413:         progress = 0.0
414:         time = 0.0
```

To:

```
413:         progress = 0.99
414:         time = v.IGNORE_SECONDS_AT_START + 1
```
No other changes required.

JC.

**Comment by JCalvi** [comment]
Let me know if you need any further info croneter.

My testing thus far it has been working well with these 2 lines changed.

JC

**Comment by JCalvi** [comment]
Had one item fail to mark as watched tonight, first since making above change so much better but still not 100%.

Dammit :(

**Comment by croneter** [comment]
Please try **BETA** version 2.12.0, that should solve your issue. If not, please let me know here.
