### ISSUE TITLE
Playback in native mode (direct paths) not working 

### ISSUE THREAD

**Issue by omeed321** [croneter/PlexKodiConnect#103]
Hello,
I'm really digging this addon, but unfortunately I am having an issue with playing a file when the plugin is set to native mode, whenever I click on a movie I get the error message "This file is no longer available".
I have tried doing the reset in the plugin, I have tried re installing kodi from scratch as well. I can access my files when I go to a browser and type something like \
\Desktop-X\e\Moviesshows\movies" so i think I have everything set up correctly, but the only way I am able to play files is by changing the native to addon (default).

Here is an error log:

http://paste.ubuntu.com/23164932/

**Comment by croneter** [comment]
Ehm, did you try to actually play an item? That seems missing :-). I won't see much otherwise...

**Comment by omeed321** [comment]
oops haha, let me upload that again.

http://paste.ubuntu.com/23165256/

**Comment by omeed321** [comment]
I'm noticing that it is trying the pull the file from 

"F:\Shows\The Making of the Mob\Season 1\The.Making.of.the.Mob.S01E06.mkv"

instead of

\\Desktop-XX\f\Shows\The Making of the Mob\Season 1\The.Making.of.the.Mob.S01E06.mkv"

could that be the problem?

**Comment by croneter** [comment]
Yes! See https://github.com/croneter/PlexKodiConnect/wiki/Direct-Paths#how-to-set-everything-up

You missed the step where you need to tell Plex to get Media via `\\Desktop-XX\f\Shows\` instead of `F:\Shows\`. Follow https://support.plex.tv/hc/en-us/articles/201154537-Move-Media-Content-to-a-New-Location

**Comment by omeed321** [comment]
Thank you very much, that fixed it!

However it is only working on my PC, no matter what I do on the shield I am still running into the same problem, both with spmc and kodi, even after reinstalling both from scratch.

"unix_err:'d' error : 'Permission denied'"

that is the error I see in my logs

**Comment by croneter** [comment]
Well yes, again https://github.com/croneter/PlexKodiConnect/wiki/Direct-Paths#how-to-set-everything-up

* You will probably need credentials to connect to your network share, a username and password. Go to Connection in the settings, then Enter network credentials. Mind that everything is case sensitive!

**Comment by omeed321** [comment]
I have tried entering the network details as well, both with IP and the server name but I am still running into the same issue, and at the begining of the sync, I get an error message saying 

"Kodi can't locate file 
\\DESKTOP-TTQR88E\d\Movies\xxx.mkv
Please verify the path, You may need to verify your network credentials in the addon settings or use different plex paths"

Is it possible kodi is leaving anything behind on my shield tv even though i uninstall it completely? I am really not sure whats going wrong because I'm following the exact steps I did on my PC which works fine.

**Comment by croneter** [comment]
For your network credentials, only enter `DESKTOP-TTAR88E`. Do NOT include the path. 

Alternatively, use Kodi to navigate to your PMS, until it asks you for credentials

**Comment by croneter** [comment]
You DID  say that you can access `\DESKTOP-TTQR88E\d\Movies\xxx.mkv` from another computer, after all

**Comment by omeed321** [comment]
"DESKTOP-TTQR88E" is what im typing in, I've also tried typing the IP. I know for a fact that I am entering the right username and password so I have no idea why its still giving me errors. Is it possible there's some sort of firewall or setting on the server pc that is not letting me connect to it even though I am entering the right info in? This is very strange.

**Comment by omeed321** [comment]
Alternatively, use Kodi to navigate to your PMS, until it asks you for credentials

I am a bit confused what you meant by this, could you explain further? I am able to view and play the files in kodi with the smb browser when I enter the username and password to my server

**Comment by croneter** [comment]
OK, the smb browser is what I meant. It's good that you're able to play files like that. 

Please try playing using PKC, capture the log and share it here (all of it). Thx

**Comment by omeed321** [comment]
Alright here is the log

http://paste.ubuntu.com/23169274/

I notice this error

XFILE::CWin32SMBDirectory::ConnectAndAuthenticate: Username/password combination was not accepted by "\\Desktop-ttqr88e\e" when trying to connect without username and without password

but I am 100% sure that I am not only entering the password in but it is also the correct username/password since it works on atleast one of the computers I've set up on my LAN, I just don't understand why none of my other devices work. Would it help if I posted the logs from the working PC playing a file?

**Comment by croneter** [comment]
That's what I meant with "only plug-in Desktop-ttqr88e as hostname" - you plugged in an additional `\e`. 

Try this:
- Delete `password.xml` from your Kodi userdata folder (http://kodi.wiki/view/userdata)
- Restart Kodi
- Use the Kodi smb browser to navigate to your Plex library and play a movie. It should ask you for username and password at some point. Make sure that you do have access
- Don't do anything else password-wise, PKC should now work if you configured it correctly

**Comment by croneter** [comment]
By the way - of course you'll have issues only on remote computers. If the media is on the same computer, you usually already have access, no matter if you plug-in a wrong hostname

**Comment by omeed321** [comment]
I just followed your instructions with deleting the password.xml and re entering it in the smb browser of kodi and I was able to view and play all the files, but when I went back into the plex plugin I kept getting the same error.

I am really not sure why its putting an additional E next to my hostname when I am not entering that at all, I promise I am only entering the host name itself and nothing more. "Desktop-ttqr88e" maybe the fact that this is happening is whats causing all the errors? The "E" it is adding is the name of one of my hard drives.

Also, the one windows computer that I got it working on is also remote, I am not sure if it would help if I sent the logs to you of it working but if it would let me know.

**Comment by croneter** [comment]
Go to your PKC settings
- Make sure that you enabled `Replace Plex UNC paths` (and only that) under Customize Paths
- Make sure that `Playback mode` is set to `Native (direct paths)` under Sync Options
- Go to Advanced, then hit the red `Partial or full reset of Database and PKC`. Choose YES, then YES, then NO

**Comment by omeed321** [comment]
I just followed the exact steps you said but I still ran into the same issue. I even went as far as to re installing everything and I still get the same error. At this point im thinking that there's something on my server side thats not letting the pc's connect, I just don't understand why one works and all the others don't

**Comment by croneter** [comment]
Nono, I'm pretty sure it's a configuration issue. After having completed the last steps above, can you please upload another log where you try to play a couple of different items?

**Comment by omeed321** [comment]
sure, here is the error log
http://paste.ubuntu.com/23170188/

**Comment by croneter** [comment]
The paths in the Kodi database are just off. They need to show `smb://desktop-xyz/blabla` instead of `\\desktop-xyz\blabla`. I don't see anything off in the PKC source code 

Sorry, but could you please again 
- make sure that only `Replace Plex UNC paths \myNas with smb://myNas:` is on, everything else off in the PKC settings under Customize Path 
- reset and resync your Kodi database: go to Advanced, hit `Partial or full reset of Database and PKC`, then 2x yes, 1x no

**Comment by croneter** [comment]
Maybe this helps. Reboot Kodi before you do the last step and resync the database

**Comment by omeed321** [comment]
I just followed the previous steps again but ran into the same issue unfortunately. How do I resync the database?

**Comment by croneter** [comment]
Reboot Kodi! 

Then go to Advanced, hit `Partial or full reset of Database and PKC`, then 2x yes, 1x no

**Comment by omeed321** [comment]
After doing that a few times I got it working on another pc that wasn't working before, but no matter what I do I can't get it working on spmc on android tv.

Since I keep getting an error when I try to upload a log via spmc, here is the error log from kodi installed on my shield tv, the error it gives looks different. I also keep getting an error message saying "Webserver failed to start" when I use Kodi, doesn't happen with spmc though.

**Comment by croneter** [comment]
Webserver is another matter. On your shield TV, change the webserver port to another number under `(Kodi) Settings → Services → Webserver → Allow control of Kodi via HTTP` as detailed here: http://kodi.wiki/view/webserver#Enabling_the_webserver


Regarding Playback: I'm seeing again
````
16:34:56 T:1756825904   ERROR: SMBDirectory->GetDirectory: Unable to open directory : 'smb://Desktop-ttqr88e/f/Movies' unix_err:'d' error : 'Permission denied'
```
Your permissions are simply bottched, ain't an issue of PKC. 

On your shield, can you use the Kodi smb browser, navigate to `smb://Desktop-ttqr88e/f/Movies/The.Grand.Budapest.Hotel.mkv` and play it?

**Comment by omeed321** [comment]
Thank you, that fixed the webserver error.

I can play the file fine when I go to the file browser then into smb, both on kodi and spmc via the shield tv. I also took a look at the passwords.xml file to make sure I wasn't having the same problem as 

https://github.com/croneter/PlexKodiConnect/issues/72

but when I look at it the username:password and the server name are what they should be.

**Comment by croneter** [comment]
Just to stress this, I don't think this is PKC related at all. Could you please share your passwords.xml here on github, of course with your usernames and passwords redacted?

**Comment by omeed321** [comment]
yea at this point Im pretty sure its an issue with my setup, if it was with the plugin more people would be posting about it.

here is what is in the xml file.

<passwords>
  <path>
    <from pathversion="1">smb:\\DESKTOP-TTQR88E/</from>
    <to pathversion="1">smb:\\USER:PASS@DESKTOP-TTQR88E/</to>
   </path>
 </passwords>

**Comment by croneter** [comment]
I take it that this is the ONLY entry? 

Try changing all backslashes `\` to forward slashes, so 
```
<passwords>
  <path>
    <from pathversion="1">smb://DESKTOP-TTQR88E/</from>
    <to pathversion="1">smb://USER:PASS@DESKTOP-TTQR88E/</to>
   </path>
 </passwords>
```

**Comment by omeed321** [comment]
Just tried that and reset PKC without reseting the settings but still having the same problem :(

**Comment by omeed321** [comment]
yep, it is the only entry

**Comment by croneter** [comment]
Darn! You did try rebooting Kodi your shield after having changed to slashes?

**Comment by omeed321** [comment]
Yep, when I reset the pkc it also rebooted kodi. I just checked and I see the slashes have stuck. Could it be an issue with my server blocking connections from android or something? I've gotten it to work on both of my windows pc's that I have access to (not including the server) but on both my shield tv and my android phone I get the same error saying the file is not available.

**Comment by croneter** [comment]
No - you could play The Grand Budapest Hotel on the shield, on Kodi, by navigating directly to the file and playing it.  Correct? 

Smells like a capitalization issue,because windows works, Linux does not. Is `DESKTOP-TTQR88E/` all in capital letters? If not, try changing that in passwords.xml to MATCH the capitalization EXACTLY

**Comment by omeed321** [comment]
Yep, I can play all the files perfectly when I browse through kodi or spmc, I also made sure all the letters are in capital, but do I need to include the slash at the end when typing it in?

**Comment by croneter** [comment]
Regarding capitalization: use exactly the same capitalization as on your PMS. On your computer `DESKTOP-TTQR88E`, run the windows command prompt "cmd.exe", then type `hostname`. Make sure you're using the capitalization you're seeing there

Try entering without the last slash. So passwords.xml should look like 
```
<passwords>
  <path>
    <from pathversion="1">smb://DESKTOP-TTQR88E</from>
    <to pathversion="1">smb://USER:PASS@DESKTOP-TTQR88E</to>
   </path>
 </passwords>
```
with the correct capitalization for `DESKTOP-TTQR88E` that cmd told you

**Comment by omeed321** [comment]
YES!!!! Removing those darn slashes finally allow it to direct play, thank you so much, I appreciate it.

**Comment by croneter** [comment]
Darn! Still getting this?
```
16:34:56 T:1756825904 ERROR: SMBDirectory->GetDirectory: Unable to open directory : 'smb://Desktop-ttqr88e/f/Movies' unix_err:'d' error : 'Permission denied' 
````

**Comment by croneter** [comment]
Maybe this helps? 
https://martinvanbeurden.nl/blog/xbmckodi-and-smb-access-denied/

**Comment by omeed321** [comment]
I just tried the steps in the article you mentioned, but after reseting kodi I still ran into the same issue. Would it help if I formatted my server with a new copy of windows? It's the last thing I wanna do but if it would make it work I wouldn't mind.

**Comment by croneter** [comment]
I would not do that.  This maybe? 

http://forum.kodi.tv/showthread.php?tid=184785&pid=1615607#pid1615607

**Comment by croneter** [comment]
Did it work? If yes, what fixed it?

**Comment by omeed321** [comment]
sorry I forgot to reply, I tried doing what the link said but after doing a reset it still didn't work, it was becoming so frustrating I just ended up setting it back to add on mode and left it there.

Even the plugin creates a folder called "plex" in my kodi library and I am able to navigate all the files fine and play everything, but as soon as I try to do it through the plugin itself I get the same error again.
